### ISSUE TITLE
请问是在哪里下载的？

### ISSUE THREAD

**Issue by duanshuai007** [mbcc2006/GeoLiteCity-data#1]
readme里面的地址我打开只有404错误

**Comment by mbcc2006** [comment]
以前从官网下的,一直留在服务器,后来官网下线了,放上来给需要的人用啊

**Comment by leojonathanoh** [comment]
Any license for re-distribution of this file? Maxmind deprecated the GeoIP earlier this year, but they didn't mention anything about redistributing this. I assume they don't care about it anymore?
